# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Down'), (2, 'No Connect'), (3, 'Error')], null=True, verbose_name='\u670d\u52a1\u5668\u72b6\u6001'),
        ),
    ]
