# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181015_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='switch',
            name='up_port',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u6c47\u805a\u63a5\u53e3'),
        ),
    ]
